version: "3.8"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    # volumes:
    #   - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - mongo
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
      - type: volume
        source: mongo_config
        target: /data/configdb
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - mongo
    depends_on:
      - mongo
networks:
  mongo:
    name: mongo

volumes:
  mongo_data:
    name: mongo_data
  mongo_config:
    name: mongo_config